# Generated by Django 2.2.1 on 2021-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nulo', max_length=200)),
                ('namefantasy', models.CharField(default='nulo', max_length=200)),
                ('sigla', models.CharField(default='nulo', max_length=8)),
                ('partido', models.CharField(default='nulo', max_length=8)),
                ('state', models.CharField(default='nulo', max_length=4)),
                ('yearInput', models.CharField(default='nulo', max_length=4)),
                ('yearOut', models.CharField(default='nulo', max_length=4)),
                ('email', models.CharField(default='nulo', max_length=200)),
                ('url', models.URLField(default='nulo', verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nulo', max_length=200)),
                ('qtd_processos', models.IntegerField(blank=True, null=True)),
                ('processo', models.CharField(default='nulo', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarioBase', models.CharField(default='nulo', max_length=12)),
                ('salarioLiquido', models.CharField(default='nulo', max_length=8)),
                ('ferias', models.CharField(default='nulo', max_length=8)),
                ('impostoRenda', models.CharField(default='nulo', max_length=8)),
                ('graficacaoNatalina', models.CharField(default='nulo', max_length=8)),
                ('vantagensPessoais', models.CharField(default='nulo', max_length=8)),
                ('auxilios', models.CharField(default='nulo', max_length=8)),
                ('diarias', models.CharField(default='nulo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PresencaPlenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSessoes', models.CharField(default='nulo', max_length=4)),
                ('presencas', models.CharField(default='nulo', max_length=4)),
                ('ausenciasJustificadas', models.CharField(default='nulo', max_length=4)),
                ('ausenciasNaoJustificadas', models.CharField(default='nulo', max_length=4)),
                ('politico', models.ForeignKey(null=True, on_delete=False, related_name='presencaplenario', to='politica.Politico')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='nulo', max_length=10)),
                ('presencaInfo', models.CharField(default='nulo', max_length=30)),
                ('politico', models.ForeignKey(null=True, on_delete=False, related_name='presenca', to='politica.Politico')),
            ],
        ),
        migrations.CreateModel(
            name='Biograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(default='nulo', max_length=200)),
                ('schooling', models.CharField(default='nulo', max_length=300)),
                ('politico', models.ForeignKey(null=True, on_delete=False, related_name='biograph', to='politica.Politico')),
            ],
        ),
    ]
