# Generated by Django 2.2.1 on 2021-02-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes_deputados', models.CharField(default='nulo', max_length=200)),
                ('gastos_total', models.CharField(default='nulo', max_length=20)),
            ],
        ),
    ]
