# Generated by Django 2.2.1 on 2021-02-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0002_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='link_para_camara',
            field=models.CharField(default='nulo', max_length=200),
        ),
    ]
