# Generated by Django 2.2.1 on 2021-03-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0003_gastos_link_para_camara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='nomes_deputados',
        ),
        migrations.AddField(
            model_name='gastos',
            name='politico',
            field=models.ForeignKey(null=True, on_delete=False, related_name='gasto', to='politica.Politico'),
        ),
    ]
