# Generated by Django 2.2.1 on 2021-03-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0004_auto_20210312_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='politico',
        ),
        migrations.DeleteModel(
            name='Processos',
        ),
        migrations.AlterModelOptions(
            name='politico',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='Presenca',
        ),
    ]
