# Generated by Django 2.2.1 on 2021-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0005_auto_20210314_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes',
            field=models.CharField(default='nulo', max_length=8),
        ),
    ]
