# Generated by Django 2.2.1 on 2021-03-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0006_remuneracao_outrasremuneracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='politico',
            field=models.ForeignKey(null=True, on_delete=False, related_name='remuneracao', to='politica.Politico'),
        ),
    ]
