# Generated by Django 2.2.1 on 2021-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0007_remuneracao_politico'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina2',
            field=models.CharField(default='nulo', max_length=8),
        ),
    ]
