# Generated by Django 2.2.1 on 2021-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0008_auto_20210319_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios32',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina22',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase2',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido2',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais2',
            field=models.CharField(default='nulo', max_length=8),
        ),
    ]
