# Generated by Django 2.2.1 on 2021-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0009_auto_20210322_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios310',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios311',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios312',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios33',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios34',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios35',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios36',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios37',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios38',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios39',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='auxilios9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='diarias9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='ferias9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacaoNatalina9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina210',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina211',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina212',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina23',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina24',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina25',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina26',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina27',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina28',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='graficacao_natalina29',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='impostoRenda9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='outrasRemuneracoes9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase10',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase11',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase12',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase3',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase4',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase5',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase6',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase7',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase8',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioBase9',
            field=models.CharField(default='nulo', max_length=12),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='salarioLiquido9',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais10',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais11',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais12',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais3',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais4',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais5',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais6',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais7',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais8',
            field=models.CharField(default='nulo', max_length=8),
        ),
        migrations.AddField(
            model_name='remuneracao',
            name='vantagensPessoais9',
            field=models.CharField(default='nulo', max_length=8),
        ),
    ]
