# Generated by Django 2.2.1 on 2021-03-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0010_auto_20210322_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remuneracao',
        ),
    ]
