# Generated by Django 2.2.1 on 2021-03-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0011_delete_remuneracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='politico',
            name='_id',
            field=models.CharField(default='nulo', max_length=6),
        ),
    ]
