# Generated by Django 2.2.1 on 2021-03-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0012_politico__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politico',
            name='_id',
        ),
    ]
