# Generated by Django 2.2.1 on 2021-03-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0013_remove_politico__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotosNominais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='nulo', verbose_name='Link')),
                ('votos_nominais', models.CharField(default='nulo', max_length=3)),
                ('politico', models.ForeignKey(null=True, on_delete=False, related_name='votosnominais', to='politica.Politico')),
            ],
        ),
    ]
