# Generated by Django 2.2.1 on 2021-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politica', '0014_votosnominais'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmendasAprovadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emenda_maior', models.CharField(default='nulo', max_length=255)),
                ('autorizado_maior', models.CharField(default='nulo', max_length=20)),
                ('empenhado_maior', models.CharField(default='nulo', max_length=20)),
                ('pago_maior', models.CharField(default='nulo', max_length=20)),
                ('emenda_media', models.CharField(default='nulo', max_length=255)),
                ('autorizado_media', models.CharField(default='nulo', max_length=20)),
                ('empenhado_media', models.CharField(default='nulo', max_length=20)),
                ('pago_media', models.CharField(default='nulo', max_length=20)),
                ('emenda_menor', models.CharField(default='nulo', max_length=255)),
                ('autorizado_menor', models.CharField(default='nulo', max_length=20)),
                ('empenhado_menor', models.CharField(default='nulo', max_length=20)),
                ('pago_menor', models.CharField(default='nulo', max_length=20)),
                ('url', models.URLField(default='nulo', verbose_name='Link')),
                ('politico', models.ForeignKey(null=True, on_delete=False, related_name='emendasaprovadas', to='politica.Politico')),
            ],
        ),
    ]
